#!/bin/bash

function check {
	if [ -z ${DB_DRIVER+x} ]; then echo "DB_DRIVER isn't set in the environment variables"; exit 1; fi
	if [ -z ${DB_HOSTNAME+x} ]; then echo "DB_HOSTNAME isn't set in the environment variables"; exit 1; fi
	if [ -z ${DB_USERNAME+x} ]; then echo "DB_USERNAME isn't set in the environment variables"; exit 1; fi
	if [ -z ${DB_PASSWORD+x} ]; then echo "DB_PASSWORD isn't set in the environment variables"; exit 1; fi
	if [ -z ${DB_DATABASE+x} ]; then echo "DB_DATABASE isn't set in the environment variables"; exit 1; fi
	if [ -z ${DB_PORT+x} ]; then echo "DB_PORT isn't set in the environment variables"; exit 1; fi
}

function default {
	# LuckPerms
	sed -i -e "s/storage-method: .*/$(echo storage-method: h2)/g" plugins/LuckPerms/config.yml;
	sed -i -e "s/address: .*/$(echo address: localhost)/g" plugins/LuckPerms/config.yml;
	sed -i -e "s/database: .*/$(echo database: minecraft)/g" plugins/LuckPerms/config.yml;
	sed -i -e "s/username: .*/$(echo username: root)/g" plugins/LuckPerms/config.yml;
	sed -i -e "s/password: .*/$(echo password: '')/g" plugins/LuckPerms/config.yml;

	# Novswar
	sed -i -e "s/connector: .*/$(echo connector: sqlite)/g" plugins/novswar/core.yml;
	sed -i -e "s/hostname: .*/$(echo hostname: localhost)/g" plugins/novswar/core.yml;
	sed -i -e "s/port: .*/$(echo port: 3306)/g" plugins/novswar/core.yml;
	sed -i -e "s/database: .*/$(echo database: example_database)/g" plugins/novswar/core.yml;
	sed -i -e "s/username: .*/$(echo username: example_user)/g" plugins/novswar/core.yml;
	sed -i -e "s/password: .*/$(echo password: example_password)/g" plugins/novswar/core.yml;

	# WorldGuard
	sed -i -e "s/use: .*/$(echo use: false)/g" plugins/WorldGuard/config.yml;
	sed -i -e "s@dsn: .*@$(echo dsn: jdbc:mysql://localhost/worldguard)@g" plugins/WorldGuard/config.yml;
	sed -i -e "s/username: .*/$(echo username: worldguard)/g" plugins/WorldGuard/config.yml;
	sed -i -e "s/password: .*/$(echo password: worldguard)/g" plugins/WorldGuard/config.yml;
	sed -i -e "s/table-prefix: .*/$(echo table-prefix: '')/g" plugins/WorldGuard/config.yml;
	exit 0;
}

check

if [ "$1" == "revert" ]; then
	echo Reverting... 
	default
fi

# LuckPerms
sed -i -e "s/storage-method: .*/$(echo storage-method: $DB_DRIVER)/g" plugins/LuckPerms/config.yml;
sed -i -e "s/address: .*/$(echo address: $DB_HOSTNAME:$DB_PORT)/g" plugins/LuckPerms/config.yml;
sed -i -e "s/database: .*/$(echo database: $DB_DATABASE)/g" plugins/LuckPerms/config.yml;
sed -i -e "s/username: .*/$(echo username: $DB_USERNAME)/g" plugins/LuckPerms/config.yml;
sed -i -e "s/password: .*/$(echo password: $DB_PASSWORD)/g" plugins/LuckPerms/config.yml;

# Novswar
sed -i -e "s/connector: .*/$(echo connector: $DB_DRIVER)/g" plugins/novswar/core.yml;
sed -i -e "s/hostname: .*/$(echo hostname: $DB_HOSTNAME)/g" plugins/novswar/core.yml;
sed -i -e "s/port: .*/$(echo port: $DB_PORT)/g" plugins/novswar/core.yml;
sed -i -e "s/database: .*/$(echo database: $DB_DATABASE)/g" plugins/novswar/core.yml;
sed -i -e "s/username: .*/$(echo username: $DB_USERNAME)/g" plugins/novswar/core.yml;
sed -i -e "s/password: .*/$(echo password: $DB_PASSWORD)/g" plugins/novswar/core.yml;

# WorldGuard
sed -i -e "s/use: false/$(echo use: true)/g" plugins/WorldGuard/config.yml;
sed -i -e "s@dsn: .*@$(echo dsn: jdbc:$DB_DRIVER://$DB_HOSTNAME:$DB_PORT/$DB_DATABASE)@g" plugins/WorldGuard/config.yml;
sed -i -e "s/username: .*/$(echo username: $DB_USERNAME)/g" plugins/WorldGuard/config.yml;
sed -i -e "s/password: .*/$(echo password: $DB_PASSWORD)/g" plugins/WorldGuard/config.yml;
sed -i -e "s/table-prefix: .*/$(echo table-prefix: wg_)/g" plugins/WorldGuard/config.yml;
